# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

encoding: utf-8 # Make sure the encoding is right
lang: en-US # Set the site language
title: WALLSEC GmbH
email: contact@wallsec.de
description: >- # this means to ignore newlines until "baseurl:"
  We are a consulting company based in Walldorf, Germany, helping
  customers run secure and compliant operations. We focus on SAP on-premise
  products and SAP Cloud services and strive to provide the best service to our customers.
baseurl: ""
url: "ws-int.gihub.io"
logo: "/assets/logos/wallsec.png" # Site logo, also used in jekyll-seo-tag
repo: "https://github.com/wallsec/"
email: "contact@wallsec.de"
# google_analytics: ""
# google_analytics_anonymize_ip: ""
short_name: "WALLSEC GmbH"
css_inline: false

twitter_username: wallsec_de
github_username:  wallsec

# Build settings
remote_theme: daviddarnes/alembic@main
plugins:
  - jekyll-feed
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-commonmark
  - jekyll-include-cache
  - jemoji
  - jekyll-remote-theme

# PAGINATE:
paginate: 2 # jekyll-paginate > items per page
paginate_path: /page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: wallsec_de # jekyll-seo-tag > Owners twitter username
author: wallsec_de # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: WALLSEC GmbH # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/wallsec_de
    - https://www.linkedin.com/company/wallsec/
    - https://github.com/wallsec

# JEKYLL SETTINS
sass:
  style: compressed
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/Berlin

# NAVIGATION
navigation_header:
- title: 🔗HOME
  url: https://wallsec.de
- title: /BLOG
  url: /
- title: /TAGS
  url: /tags/
- title: /SEARCH
  url: /search/
navigation_footer:
- title: Sitemap
  url: sitemap.xml
- title: 🔗Impress
  url: https://www.wallsec.de
- title: 🔗Privacy Statement
  url: https://www.wallsec.de/datenschutz




social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://twitter.com/wallsec_de
  LinkedIn: https://www.linkedin.com/company/wallsec
  GitHub: https://github.com/wallsec
  facebook: https://www.facebook.com/WALLSECGmbH&sa=D&sntz=1&usg=AOvVaw3mpIh4jSh8fQC3dTSQFjcN
  email: https://docs.google.com/forms/d/e/1FAIpQLSc-6HPRprxiATpJYwnovIN6dL01tMiFxRK2rFMlNoqs613KOQ/viewform?usp=sf_link
  RSS: /feed.xml

sharing_links: # Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
  Twitter: "#0d94e7"
  facebook: "#3B5998"
  Email: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
